import { User } from "@/types/main";
// import { Part } from "@/types/main";
import {Part} from "@/types/main";

export const users: User[] = [
  { id: 1, firstName: 'علی', lastName: 'امینی', email: 'ali.amini@gmail.com', date: new Date('2024-04-30') },
  { id: 2, firstName: 'مهدی', lastName: 'سهرابی', email: 'mehdi.sohrabi@gmail.com', date: new Date('2024-08-13') },
  { id: 3, firstName: 'پیام', lastName: 'محمدی', email: 'payam.mohamadi@gmail.com', date: new Date('2023-11-28') },
  { id: 4, firstName: 'فاطمه', lastName: 'عباسی', email: 'fateme.abasi@gmail.com', date: new Date('2023-04-19') },
  { id: 5, firstName: 'تینا', lastName: 'متین', email: 'tina.matin@gmail.com', date: new Date('2024-03-01') },
  { id: 6, firstName: 'امیر', lastName: 'شریفی', email: 'amir.sharifi@gmail.com', date: new Date('2024-05-12') },
  { id: 7, firstName: 'سارا', lastName: 'حسینی', email: 'sara.hosseini@gmail.com', date: new Date('2023-10-10') },
  { id: 8, firstName: 'رضا', lastName: 'نظری', email: 'reza.nazari@gmail.com', date: new Date('2024-01-22') },
  { id: 9, firstName: 'نرگس', lastName: 'صفری', email: 'narges.safari@gmail.com', date: new Date('2023-07-07') },
  { id: 10, firstName: 'حمید', lastName: 'کریمی', email: 'hamid.karimi@gmail.com', date: new Date('2024-09-09') },
  { id: 11, firstName: 'پریسا', lastName: 'رهنما', email: 'parisa.rahnama@gmail.com', date: new Date('2023-06-21') },
  { id: 12, firstName: 'زهرا', lastName: 'جمالی', email: 'zahra.jamali@gmail.com', date: new Date('2023-12-30') },
  { id: 13, firstName: 'علیرضا', lastName: 'میرزایی', email: 'alireza.mirzaei@gmail.com', date: new Date('2024-03-11') },
  { id: 14, firstName: 'شبنم', lastName: 'کریمی', email: 'shabnam.karimi@gmail.com', date: new Date('2024-06-01') },
  { id: 15, firstName: 'حمیده', lastName: 'عسگری', email: 'hamideh.asgari@gmail.com', date: new Date('2023-02-20') },
  { id: 16, firstName: 'رضا', lastName: 'محمدی', email: 'reza.mohammadi@gmail.com', date: new Date('2023-03-05') },
  { id: 17, firstName: 'مریم', lastName: 'نوروزی', email: 'maryam.norouzi@gmail.com', date: new Date('2024-02-14') },
  { id: 18, firstName: 'محسن', lastName: 'زارعی', email: 'mohsen.zarei@gmail.com', date: new Date('2024-04-18') },
  { id: 19, firstName: 'سمیه', lastName: 'رستمی', email: 'somayeh.rostami@gmail.com', date: new Date('2023-11-19') },
  { id: 20, firstName: 'علی', lastName: 'نیکنام', email: 'ali.niknam@gmail.com', date: new Date('2024-07-13') },
  { id: 21, firstName: 'کیانا', lastName: 'سلطانی', email: 'kiana.soltani@gmail.com', date: new Date('2023-05-15') },
  { id: 22, firstName: 'امین', lastName: 'نوری', email: 'amin.nouri@gmail.com', date: new Date('2024-03-21') },
  { id: 23, firstName: 'شیما', lastName: 'صادقی', email: 'shima.sadeghi@gmail.com', date: new Date('2023-08-11') },
  { id: 24, firstName: 'سعید', lastName: 'رضایی', email: 'saeid.rezaei@gmail.com', date: new Date('2024-11-01') },
  { id: 25, firstName: 'محمد', lastName: 'جعفری', email: 'mohammad.jafari@gmail.com', date: new Date('2023-04-25') },
  { id: 26, firstName: 'مهدیه', lastName: 'حسینی', email: 'mahdiyeh.hosseini@gmail.com', date: new Date('2024-07-29') },
  { id: 27, firstName: 'فرهاد', lastName: 'جمالی', email: 'farhad.jamali@gmail.com', date: new Date('2024-08-30') },
  { id: 28, firstName: 'آرمان', lastName: 'مرادی', email: 'arman.moradi@gmail.com', date: new Date('2023-12-01') },
  { id: 29, firstName: 'افسانه', lastName: 'قادری', email: 'afsaneh.ghaderi@gmail.com', date: new Date('2024-03-14') },
  { id: 30, firstName: 'پیمان', lastName: 'راد', email: 'peyman.rad@gmail.com', date: new Date('2023-09-07') },
  { id: 31, firstName: 'مهسا', lastName: 'سجادی', email: 'mahsaj.sajadi@gmail.com', date: new Date('2024-10-18') },
  { id: 32, firstName: 'سحر', lastName: 'ابراهیمی', email: 'sahar.ebrahimi@gmail.com', date: new Date('2023-01-30') },
  { id: 33, firstName: 'میلاد', lastName: 'افتخاری', email: 'milad.eftekhari@gmail.com', date: new Date('2024-03-03') },
  { id: 34, firstName: 'لیلا', lastName: 'شایسته', email: 'leila.shayesteh@gmail.com', date: new Date('2024-08-17') },
  { id: 35, firstName: 'امید', lastName: 'صفایی', email: 'omid.safaei@gmail.com', date: new Date('2024-09-09') },
  { id: 36, firstName: 'نازی', lastName: 'خراسانی', email: 'nazi.khorasani@gmail.com', date: new Date('2023-03-22') },
  { id: 37, firstName: 'نوید', lastName: 'سالاری', email: 'navid.salari@gmail.com', date: new Date('2024-05-14') },
  { id: 38, firstName: 'طیبه', lastName: 'بابایی', email: 'tayebeh.babaei@gmail.com', date: new Date('2024-06-30') },
  { id: 39, firstName: 'مهتاب', lastName: 'یزدانی', email: 'mahtab.yazdani@gmail.com', date: new Date('2023-12-11') },
  { id: 40, firstName: 'مینا', lastName: 'فلاح', email: 'mina.fallah@gmail.com', date: new Date('2023-04-29') },
  { id: 41, firstName: 'کریم', lastName: 'سلیمی', email: 'karim.salimi@gmail.com', date: new Date('2024-05-23') },
  { id: 42, firstName: 'مژگان', lastName: 'کاظمی', email: 'mozhgan.kazemi@gmail.com', date: new Date('2023-08-05') },
  { id: 43, firstName: 'علیرضا', lastName: 'مرادی', email: 'alireza.moradi@gmail.com', date: new Date('2023-02-02') },
  { id: 44, firstName: 'شیوا', lastName: 'قاسمی', email: 'shiva.ghasemi@gmail.com', date: new Date('2024-01-27') },
  { id: 45, firstName: 'فائزه', lastName: 'یزدانی', email: 'faezeh.yazdani@gmail.com', date: new Date('2024-09-25') },
  { id: 46, firstName: 'عباس', lastName: 'ساعی', email: 'abbas.saei@gmail.com', date: new Date('2024-02-18') },
  { id: 47, firstName: 'احسان', lastName: 'شایگان', email: 'ehsan.shaygan@gmail.com', date: new Date('2023-07-31') },
  { id: 48, firstName: 'ندا', lastName: 'مرادی', email: 'neda.moradi@gmail.com', date: new Date('2023-06-06') },
  { id: 49, firstName: 'رها', lastName: 'اکبری', email: 'raha.akbari@gmail.com', date: new Date('2024-05-10') },
  { id: 50, firstName: 'سهیل', lastName: 'جمشیدی', email: 'soheil.jamshidi@gmail.com', date: new Date('2023-10-15') }
];

// export const parts: Part[] = [
//   { id: 1, partName: 'مرسدس بنز', founded: "1926", country: 'آلمان', industry: 'وسایل نقلیه' },
//   { id: 2, partName: 'ایسوس', founded: "1989", country: 'تایوان', industry: 'سخت‌افزار رایانه' },
//   { id: 3, partName: 'تویوتا', founded: "1937", country: 'ژاپن', industry: 'وسایل نقلیه' },
//   { id: 4, partName: 'اپل', founded: "1976", country: 'ایالات متحده آمریکا', industry: 'سخت‌افزار رایانه' },
//   { id: 5, partName: 'بوش', founded: "1886", country: 'آلمان', industry: 'لوازم برقی' },
//   { id: 6, partName: 'سامسونگ', founded: "1938", country: 'کره جنوبی', industry: 'لوازم الکترونیکی' },
//   { id: 7, partName: 'هیوندای', founded: "1967", country: 'کره جنوبی', industry: 'وسایل نقلیه' },
//   { id: 8, partName: 'کوکاکولا', founded: "1892", country: 'ایالات متحده آمریکا', industry: 'نوشیدنی' },
//   { id: 9, partName: 'نایک', founded: "1964", country: 'ایالات متحده آمریکا', industry: 'پوشاک' },
//   { id: 10, partName: 'پپسی', founded: "1898", country: 'ایالات متحده آمریکا', industry: 'نوشیدنی' },
//   { id: 11, partName: 'مایکروسافت', founded: "1975", country: 'ایالات متحده آمریکا', industry: 'نرم‌افزار' },
//   { id: 12, partName: 'سونی', founded: "1946", country: 'ژاپن', industry: 'لوازم الکترونیکی' },
//   { id: 13, partName: 'هواوی', founded: "1987", country: 'چین', industry: 'مخابرات' },
//   { id: 14, partName: 'شورلت', founded: "1911", country: 'ایالات متحده آمریکا', industry: 'وسایل نقلیه' },
//   { id: 15, partName: 'آدیداس', founded: "1949", country: 'آلمان', industry: 'پوشاک' },
//   { id: 16, partName: 'پاناسونیک', founded: "1918", country: 'ژاپن', industry: 'لوازم الکترونیکی' },
//   { id: 17, partName: 'مک‌دونالد', founded: "1940", country: 'ایالات متحده آمریکا', industry: 'غذا' },
//   { id: 18, partName: 'آمازون', founded: "1994", country: 'ایالات متحده آمریکا', industry: 'تجارت الکترونیک' },
//   { id: 19, partName: 'فورد', founded: "1903", country: 'ایالات متحده آمریکا', industry: 'وسایل نقلیه' },
//   { id: 20, partName: 'کاترپیلار', founded: "1925", country: 'ایالات متحده آمریکا', industry: 'ماشین‌آلات سنگین' },
//   { id: 21, partName: 'اینتل', founded: "1968", country: 'ایالات متحده آمریکا', industry: 'سخت‌افزار رایانه' },
//   { id: 22, partName: 'دل', founded: "1984", country: 'ایالات متحده آمریکا', industry: 'سخت‌افزار رایانه' },
//   { id: 23, partName: 'لنوو', founded: "1984", country: 'چین', industry: 'سخت‌افزار رایانه' },
//   { id: 24, partName: 'ولوو', founded: "1927", country: 'سوئد', industry: 'وسایل نقلیه' },
//   { id: 25, partName: 'گودیر', founded: "1898", country: 'ایالات متحده آمریکا', industry: 'لاستیک' },
//   { id: 26, partName: 'گوگل', founded: "1998", country: 'ایالات متحده آمریکا', industry: 'اینترنت' },
//   { id: 27, partName: 'پژو', founded: "1810", country: 'فرانسه', industry: 'وسایل نقلیه' },
//   { id: 28, partName: 'فولکس‌واگن', founded: "1937", country: 'آلمان', industry: 'وسایل نقلیه' },
//   { id: 29, partName: 'کاسیو', founded: "1946", country: 'ژاپن', industry: 'لوازم الکترونیکی' },
//   { id: 30, partName: 'نوکیا', founded: "1865", country: 'فنلاند', industry: 'مخابرات' },
//   { id: 31, partName: 'کداک', founded: "1888", country: 'ایالات متحده آمریکا', industry: 'عکاسی' },
//   { id: 32, partName: 'پی‌پال', founded: "1998", country: 'ایالات متحده آمریکا', industry: 'خدمات مالی' },
//   { id: 33, partName: 'پروکتر اند گمبل', founded: "1837", country: 'ایالات متحده آمریکا', industry: 'محصولات مصرفی' },
//   { id: 34, partName: 'فیلیپس', founded: "1891", country: 'هلند', industry: 'لوازم الکترونیکی' },
//   { id: 35, partName: 'پرادا', founded: "1913", country: 'ایتالیا', industry: 'پوشاک' },
//   { id: 36, partName: 'آلیانز', founded: "1890", country: 'آلمان', industry: 'بیمه' },
//   { id: 37, partName: 'پیرللی', founded: "1872", country: 'ایتالیا', industry: 'لاستیک' },
//   { id: 38, partName: 'زیمنس', founded: "1847", country: 'آلمان', industry: 'لوازم الکترونیکی' },
//   { id: 39, partName: 'هیتاچی', founded: "1910", country: 'ژاپن', industry: 'ماشین‌آلات صنعتی' },
//   { id: 40, partName: 'اوبر', founded: "2009", country: 'ایالات متحده آمریکا', industry: 'تکنولوژی' },
//   { id: 41, partName: 'نینتندو', founded: "1889", country: 'ژاپن', industry: 'بازی‌های ویدیویی' },
//   { id: 42, partName: 'کلگیت', founded: "1806", country: 'ایالات متحده آمریکا', industry: 'محصولات بهداشتی' },
//   { id: 43, partName: 'اکسون موبیل', founded: "1999", country: 'ایالات متحده آمریکا', industry: 'نفت و گاز' },
//   { id: 44, partName: 'لوریال', founded: "1909", country: 'فرانسه', industry: 'لوازم آرایشی' },
//   { id: 45, partName: 'کونیکا مینولتا', founded: "1873", country: 'ژاپن', industry: 'عکاسی و چاپ' },
//   { id: 46, partName: 'شل', founded: "1907", country: 'هلند', industry: 'نفت و گاز' },
//   { id: 47, partName: 'آئودی', founded: "1909", country: 'آلمان', industry: 'وسایل نقلیه' },
//   { id: 48, partName: 'رولکس', founded: "1905", country: 'سوئیس', industry: 'ساعت‌سازی' },
//   { id: 49, partName: 'پرشیا خودرو', founded: "2005", country: 'ایران', industry: 'خدمات خودرو' },
//   { id: 50, partName: 'یاماها', founded: "1887", country: 'ژاپن', industry: 'موسیقی و وسایل نقلیه' }
// ];
export const elevatorParts: Part[] = [
  { id:1, partType: 'موتور', partBrand : 'AEG'},
  { id:2, partType: 'موتور', partBrand : 'ALBERTO SASSI'},
  { id:3, partType: 'موتور', partBrand : 'BEHRAN'},
  { id:4, partType: 'موتور', partBrand : 'BLUE LIGHT'},
  { id:5, partType: 'موتور', partBrand : 'ELCO'},
  { id:6, partType: 'موتور', partBrand : 'Elegance'},
  { id:7, partType: 'موتور', partBrand : 'EMF'},
  { id:8, partType: 'موتور', partBrand : 'FIA'},
  { id:9, partType: 'موتور', partBrand : 'IR20'},
  { id:10, partType: 'موتور', partBrand : 'Ital'},
  { id:11, partType: 'موتور', partBrand : 'MEGA'},
  { id:12, partType: 'موتور', partBrand : 'MONA DRIVE'},
  { id:13, partType: 'موتور', partBrand : 'MONTANARI'},
  { id:14, partType: 'موتور', partBrand : 'Omega'},
  { id:15, partType: 'موتور', partBrand : 'Primo'},
  { id:16, partType: 'موتور', partBrand : 'SICOR'},
  { id:17, partType: 'موتور', partBrand : 'SWR'},
  { id:18, partType: 'موتور', partBrand : 'VEBER'},
  { id:19, partType: 'موتور', partBrand : 'WITTUR'},
  { id:20, partType: 'موتور', partBrand : 'XINDA'},
  { id:21, partType: 'موتور', partBrand : 'Ziehl Abegg'},
  { id:22, partType: 'فلکه هرزگرد', partBrand : 'آسان شایان'},
  { id:23, partType: 'فلکه هرزگرد', partBrand : 'پارس صنعت'},
  { id:24, partType: 'فلکه هرزگرد', partBrand : 'پرشیا'},
  { id:25, partType: 'فلکه هرزگرد', partBrand : 'سخاوت'},
  { id:26, partType: 'فلکه هرزگرد', partBrand : 'کوثر'},
  { id:27, partType: 'فلکه هرزگرد', partBrand : 'محراب فراز'},
  { id:28, partType: 'کابین', partBrand : 'الکسانی'},
  { id:29, partType: 'کابین', partBrand : 'پارس'},
  { id:30, partType: 'کابین', partBrand : 'پریسما'},
  { id:31, partType: 'کابین', partBrand : 'جنرال'},
  { id:32, partType: 'کابین', partBrand : 'طبسی'},
  { id:33, partType: 'کابین', partBrand : 'عبادت'},
  { id:34, partType: 'کابین', partBrand : 'کابین پلاس'},
  { id:35, partType: 'کابین', partBrand : 'وحیدی'},
  { id:36, partType: 'پاراشوت', partBrand : 'DANYATEK'},
  { id:37, partType: 'پاراشوت', partBrand : 'METRO PLAST'},
  { id:38, partType: 'پاراشوت', partBrand : 'SCHINDLER'},
  { id:39, partType: 'پاراشوت', partBrand : 'WITTUR'},
  { id:40, partType: 'پاراشوت', partBrand : 'آسان شایان'},
  { id:41, partType: 'پاراشوت', partBrand : 'بهرو صنعت'},
  { id:42, partType: 'پاراشوت', partBrand : 'فراز لطفی'},
  { id:43, partType: 'درب', partBrand : 'Fermator'},
  { id:44, partType: 'درب', partBrand : 'fupa'},
  { id:45, partType: 'درب', partBrand : 'Prisma'},
  { id:46, partType: 'درب', partBrand : 'Selecom'},
  { id:47, partType: 'درب', partBrand : 'Total'},
  { id:48, partType: 'درب', partBrand : 'افرند'},
  { id:49, partType: 'درب', partBrand : 'آریان سیستم رو'},
  { id:50, partType: 'درب', partBrand : 'پارس'},
  { id:51, partType: 'درب', partBrand : 'روانکار سماتیک'},
  { id:52, partType: 'درب', partBrand : 'سپاهان رو'},
  { id:53, partType: 'درب', partBrand : 'سیما تکسان'},
  { id:54, partType: 'درب', partBrand : 'فلوئنت'},
  { id:55, partType: 'درب', partBrand : 'ویتال'},
  { id:56, partType: 'درب', partBrand : 'کیوان'},
  { id:57, partType: 'درب', partBrand : 'یاران'},
  { id:58, partType: 'قفل', partBrand : 'CAN LIFT'},
  { id:59, partType: 'قفل', partBrand : 'INT'},
  { id:60, partType: 'قفل', partBrand : 'ONSA'},
  { id:61, partType: 'قفل', partBrand : 'SCHINDLER'},
  { id:62, partType: 'قفل', partBrand : 'ZORLO'},
  { id:63, partType: 'قفل', partBrand : 'آسان شایان'},
  { id:64, partType: 'قفل', partBrand : 'آرین سیستم رو'},
  { id:65, partType: 'قفل', partBrand : 'بهران'},
  { id:66, partType: 'قفل', partBrand : 'تاپ'},
  { id:67, partType: 'قفل', partBrand : 'سپاهان'},
  { id:68, partType: 'قفل', partBrand : 'پارت لیفت'},
  { id:69, partType: 'دیکتاتور', partBrand : 'CAN LIFT'},
  { id:70, partType: 'دیکتاتور', partBrand : 'INT'},
  { id:71, partType: 'دیکتاتور', partBrand : 'ONSA'},
  { id:72, partType: 'دیکتاتور', partBrand : 'SCHINDLER'},
  { id:73, partType: 'دیکتاتور', partBrand : 'ZORLO'},
  { id:74, partType: 'دیکتاتور', partBrand : 'آسان شایان'},
  { id:75, partType: 'دیکتاتور', partBrand : 'آرین سیستم رو'},
  { id:76, partType: 'دیکتاتور', partBrand : 'بهران'},
  { id:77, partType: 'دیکتاتور', partBrand : 'تاپ'},
  { id:78, partType: 'دیکتاتور', partBrand : 'سپاهان'},
  { id:79, partType: 'دیکتاتور', partBrand : 'پارت'},
  { id:80, partType: 'مگنت درب بازکن', partBrand : 'CAN LIFT'},
  { id:81, partType: 'مگنت درب بازکن', partBrand : 'INT'},
  { id:82, partType: 'مگنت درب بازکن', partBrand : 'ONSA'},
  { id:83, partType: 'مگنت درب بازکن', partBrand : 'SCHINDLER'},
  { id:84, partType: 'مگنت درب بازکن', partBrand : 'ZORLO'},
  { id:85, partType: 'مگنت درب بازکن', partBrand : 'آسان شایان'},
  { id:86, partType: 'مگنت درب بازکن', partBrand : 'آرین سیستم رو'},
  { id:87, partType: 'مگنت درب بازکن', partBrand : 'بهران'},
  { id:88, partType: 'مگنت درب بازکن', partBrand : 'تاپ'},
  { id:89, partType: 'مگنت درب بازکن', partBrand : 'سپاهان'},
  { id:90, partType: 'مگنت درب بازکن', partBrand : 'پارت'},
  { id:91, partType: 'ریل', partBrand : 'ASRAEI'},
  { id:92, partType: 'ریل', partBrand : 'AYGUN'},
  { id:93, partType: 'ریل', partBrand : 'CELIK'},
  { id:94, partType: 'ریل', partBrand : 'FALCON'},
  { id:95, partType: 'ریل', partBrand : 'MARAZZI'},
  { id:96, partType: 'ریل', partBrand : 'MF'},
  { id:97, partType: 'ریل', partBrand : 'MOF'},
  { id:98, partType: 'ریل', partBrand : 'MONTEFERRO'},
  { id:99, partType: 'ریل', partBrand : 'RUNFA'},
  { id:100, partType: 'ریل', partBrand : 'SAVERA'},
  { id:101, partType: 'تابلو فرمان', partBrand : 'السا'},
  { id:102, partType: 'تابلو فرمان', partBrand : 'آراد'},
  { id:103, partType: 'تابلو فرمان', partBrand : 'آرکل'},
  { id:104, partType: 'تابلو فرمان', partBrand : 'آرمان فراز'},
  { id:105, partType: 'تابلو فرمان', partBrand : 'آریان آسانسور'},
  { id:106, partType: 'تابلو فرمان', partBrand : 'پار کنترل'},
  { id:107, partType: 'تابلو فرمان', partBrand : 'داتیس'},
  { id:108, partType: 'تابلو فرمان', partBrand : 'عصر نوین'},
  { id:109, partType: 'تابلو فرمان', partBrand : 'کاسپین'},
  { id:110, partType: 'درایو', partBrand : 'Advanse (aris)'},
  { id:111, partType: 'درایو', partBrand : 'Advanse (arpack)'},
  { id:112, partType: 'درایو', partBrand : 'Arco'},
  { id:113, partType: 'درایو', partBrand : 'Arkel arcode'},
  { id:114, partType: 'درایو', partBrand : 'Arkel arcube'},
  { id:115, partType: 'درایو', partBrand : 'BLUE LIGHT'},
  { id:116, partType: 'درایو', partBrand : 'Danfos'},
  { id:117, partType: 'درایو', partBrand : 'Gefran-ADL'},
  { id:118, partType: 'درایو', partBrand : 'Gefran-VDL'},
  { id:119, partType: 'درایو', partBrand : 'HP'},
  { id:120, partType: 'درایو', partBrand : 'HP-Mount'},
  { id:121, partType: 'درایو', partBrand : 'HP-plus'},
  { id:122, partType: 'درایو', partBrand : 'I star'},
  { id:123, partType: 'درایو', partBrand : 'LG'},
  { id:124, partType: 'درایو', partBrand : 'Monarch'},
  { id:125, partType: 'درایو', partBrand : 'SBT ecomain'},
  { id:126, partType: 'درایو', partBrand : 'SBT pro'},
  { id:127, partType: 'درایو', partBrand : 'Toshiba'},
  { id:128, partType: 'درایو', partBrand : 'Yaskawa'},
  { id:129, partType: 'درایو', partBrand : 'Younic'},
  { id:130, partType: 'درایو', partBrand : 'Ziehl Abegg'},
  { id:131, partType: 'encoder', partBrand : 'Autonics'},
  { id:132, partType: 'چشمی', partBrand : 'AFP'},
  { id:133, partType: 'چشمی', partBrand : 'ADA Lift'},
  { id:134, partType: 'چشمی', partBrand : 'ERDEN'},
  { id:135, partType: 'چشمی', partBrand : 'Sonar'},
  { id:136, partType: 'چشمی', partBrand : 'SUNY'},
  { id:137, partType: 'چشمی', partBrand : 'WECO'},
  { id:138, partType: 'چشمی', partBrand : 'آرمان فراز'},
  { id:139, partType: 'چشمی', partBrand : 'آرین سیستم رو'},
  { id:140, partType: 'چشمی', partBrand : 'ناسیس'},
  { id:141, partType: 'سیم بکسل', partBrand : 'FIFER'},
  { id:142, partType: 'سیم بکسل', partBrand : 'GUSTAV WOLF'},
  { id:143, partType: 'سیم بکسل', partBrand : 'ITASIA'},
  { id:144, partType: 'گاورنر', partBrand : 'آسان شایان'},
  { id:145, partType: 'گاورنر', partBrand : 'آکیش'},
  { id:146, partType: 'گاورنر', partBrand : 'آنام'},
  { id:147, partType: 'گاورنر', partBrand : 'بهرو صنعت'},
  { id:148, partType: 'گاورنر', partBrand : 'پارس آسا'},
  { id:149, partType: 'گاورنر', partBrand : 'پارس لیفت'},
  { id:150, partType: 'گاورنر', partBrand : 'پرشیا'},
  { id:151, partType: 'گاورنر', partBrand : 'متروپلاست'},
  { id:152, partType: 'تراولینگ کابل', partBrand : 'ALKATEL'},
  { id:153, partType: 'تراولینگ کابل', partBrand : 'DAT WHYLER'},
  { id:154, partType: 'تراولینگ کابل', partBrand : 'ITASIA'},
  { id:155, partType: 'تراولینگ کابل', partBrand : 'MKS'},
  { id:156, partType: 'تراولینگ کابل', partBrand : 'ASIA'},
  { id:157, partType: 'تراولینگ کابل', partBrand : 'FERSTA'},
  { id:158, partType: 'تراولینگ کابل', partBrand : 'GOLSHANI'},
  { id:159, partType: 'نمایشگر', partBrand : 'LCD'},
  { id:160, partType: 'نمایشگر', partBrand : 'seven segment'},
  { id:161, partType: 'نمایشگر', partBrand : 'ریزشی'},
  { id:162, partType: 'نمایشگر', partBrand : 'Full serial'},
  { id:163, partType: 'شاسی', partBrand : 'پنتا'},
  { id:164, partType: 'شاسی', partBrand : 'نوین صنعت'},
  { id:165, partType: 'شاسی', partBrand : 'مدیا'},
  { id:166, partType: 'سوییچ on / off', partBrand : 'آسان شایان'},
  { id:167, partType: 'سوییچ on / off', partBrand : 'شهاب'},
  { id:168, partType: 'روغن دان', partBrand : 'KMB'},
  { id:169, partType: 'روغن دان', partBrand : 'پارس صنعت'},
  { id:170, partType: 'روغن دان', partBrand : 'یاشار لیفت'},
  { id:171, partType: 'قلاب سربکسل', partBrand : 'پارس صنعت'},
  { id:172, partType: 'قلاب سربکسل', partBrand : 'پرشیا'},
  { id:173, partType: 'قلاب سربکسل', partBrand : 'سخاوت'},
  { id:174, partType: 'قلاب سربکسل', partBrand : 'کوثر'},
  { id:175, partType: 'قلاب سربکسل', partBrand : 'محراب فراز'},
  { id:176, partType: 'over load', partBrand : 'ZORLO'},
  { id:177, partType: 'over load', partBrand : 'CENTA'},
  { id:178, partType: 'over load', partBrand : 'DINACELL'},
  { id:179, partType: 'over load', partBrand : 'turbocell'},
  { id:180, partType: 'کفشک', partBrand : 'پرشیا'},
  { id:181, partType: 'کفشک', partBrand : 'پارس صنعت'},
  { id:182, partType: 'کفشک', partBrand : 'اورچین صنعت اصفهان'},
  { id:183, partType: 'کفشک', partBrand : 'طرح اتیس'},
  { id:184, partType: 'پاوریونیت', partBrand : 'wittur'},
  { id:185, partType: 'پاوریونیت', partBrand : 'blain'},
  { id:186, partType: 'پاوریونیت', partBrand : 'moris'},
  { id:187, partType: 'پاوریونیت', partBrand : 'GMV'},
  { id:188, partType: 'پاوریونیت', partBrand : 'HL'},

];
